meta:
  repo_uri: ((git_repo_uri))
  opsman_vm_state_repo_uri: ((git_opsman_vm_state_repo_uri))
  git_tag: master
  git_private_key: ((gitlab_ssh.private_key))
  ci_docker_image: ((ci_docker_image))
  ci_docker_image_tag: ((ci_docker_image_tag))
  minio_url: ((minio_url))
  minio_access_key: ((minio_access_key))
  minio_secret_key: ((minio_secret_key))
  minio_region: ((minio_region))
  minio_bucket_for_pivotal_product: ((minio_pivnet_products_bucket))

